### ISSUE TITLE
Option to disable tsconfig-paths?

### ISSUE THREAD

**Issue by mjomble** [gtap-dev/fractal-tsx-adapter#11]
Currently, `require('tsconfig-paths').register();` is always executed, whether the project actually uses `paths` in tsconfig or not.

This can cause a "Missing baseUrl in compilerOptions. tsconfig-paths will be skipped" warning to be logged, which gets especially noisy in Jest tests.

Should we add an option to disable it? Or some other method of silencing the warning?

**Comment by mihkeleidast** [comment]
Won't fix - this adapter will soon be deprecated when the official `@frctl/react` adapter gets all issues resolved. No point in maintaining both, especially since I'm also maintaining the official one :)
